import { Meal } from "@dreamdiet/interfaces/src/index";
export const tags = {
  breakfast: "breakfast",
  lunch: "lunch",
  dinner: "dinner",
  snack: "snack",
  pre_sleep: "pre_sleep",
};

export const db: Meal[] = [
  {
    name: "Albume",
    protein: 11,
    carbs: 0.7,
    fat: 0.2,
    tags: [tags.breakfast],
  },
  {
    name: "Latte intero",
    protein: 3.5,
    carbs: 4.5,
    fat: 3.7,
    tags: [tags.breakfast],
  },
  {
    name: "Whey",
    protein: (24 / 30) * 100,
    carbs: (3 / 30) * 100,
    fat: (1.5 / 30) * 100,
    tags: [tags.snack, tags.pre_sleep, tags.breakfast],
  },
  {
    name: "Farina Avena",
    protein: 14.66,
    carbs: 65.7,
    fat: 9.12,
    tags: [tags.breakfast],
  },
  {
    name: "Olio d'oliva",
    protein: 0,
    carbs: 0,
    fat: 100,
    max_grams_per_meal: 10,
    tags: [tags.lunch, tags.dinner, tags.breakfast],
  },
  {
    name: "Petto di pollo",
    protein: 23.3,
    carbs: 0,
    fat: 0.8,
    tags: [tags.lunch, tags.dinner],
  },
  {
    name: "Riso bianco",
    protein: 6.7,
    carbs: 80.4,
    fat: 0.4,
    tags: [tags.lunch, tags.dinner],
  },
  {
    name: "Banana",
    protein: 1.1,
    carbs: 23.2,
    fat: 0.3,
    tags: [tags.snack],
  },
  {
    name: "Arancia",
    protein: 0.7,
    carbs: 10,
    fat: 0.2,
    tags: [tags.snack],
  },
  {
    name: "Yogurt intero",
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    tags: [tags.snack, tags.pre_sleep],
  },
  {
    name: "Petto di pollo Affettato",
    protein: 22,
    carbs: 0,
    fat: 1.6,
    tags: [tags.snack],
  },
  {
    name: "Vitello",
    protein: 20.7,
    carbs: 0,
    fat: 2.7,
    tags: [tags.lunch, tags.dinner],
  },
  {
    name: "Mandorle",
    protein: 21,
    carbs: 22,
    fat: 49,
    tags: [tags.snack, tags.pre_sleep],
  },
  {
    name: "Burro d'arachidi",
    protein: 25,
    carbs: 19.6,
    fat: 52,
    tags: [tags.snack, tags.pre_sleep],
  },
  {
    name: "Parmigiano Reggiano",
    protein: 38,
    carbs: 4.1,
    fat: 29,
    tags: [tags.snack, tags.pre_sleep],
  },
  {
    name: "Pane azzimo",
    protein: 10.7,
    carbs: 87,
    fat: 0.8,
    tags: [tags.snack, tags.pre_sleep, tags.breakfast, tags.lunch, tags.dinner],
  },
  {
    name: "Cioccolato Fondente 80%",
    protein: 10,
    carbs: 34,
    fat: 46,
    max_grams_per_meal: 10,
    tags: [tags.snack, tags.pre_sleep, tags.breakfast],
  },
];
