name: build-gh-pages

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build-gh-pages:
    name: ${{ matrix.command }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: yarn install

      - name: Build web
        run: yarn workspace @dreamdiet/web run build

      - name: Push build to gh-pages branch
        run: |
          git config --global user.name "EvolveYourMind bot"
          git config --global user.email "EvolveYourMind-bot@users.noreply.github.com'"
          git clone https://github.com/evolveyourmind/dreamdiet --depth 1 --branch gh-pages gh-pages
          cd gh-pages
          git rm -rf .
          cp -r ../packages/web/build/* .
          git add -A
          git commit -m "Update gh-pages"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/evolveyourmind/bb
          git push origin gh-pages
